version: 2

release:
  draft: false
  prerelease: true

before:
  hooks:
    - go mod download

builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=0
      ldflags: null
  - <<: *build_defaults
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: freebsd
    goos: [freebsd]
    goarch: [386, amd64]

checksum:
  name_template: "changelog-from-release_{{.Version}}_checksums.txt"
  algorithm: sha256

archives:
  - <<: &archives_defaults
      files:
        - README.md
        - CHANGELOG.md
        - LICENSE.txt
    id: nix
    ids: [macos, linux, freebsd]
    formats: ['tar.gz']
  - <<: *archives_defaults
    id: windows
    ids: [windows]
    formats: ['zip']

changelog:
  disable: true
