package main

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/google/go-github/v66/github"
)

type Config struct {
	Level        int
	Drafts       bool
	Prerelease   bool
	Contributors bool
	Ignore       *regexp.Regexp
	Extract      *regexp.Regexp
}

func (c *Config) filterReleases(rels []*github.RepositoryRelease) []*github.RepositoryRelease {
	i := 0
	for i < len(rels) {
		r := rels[i]
		t := r.GetTagName()
		if (c.Drafts || !r.GetDraft()) &&
			(c.Prerelease || !r.GetPrerelease()) &&
			(c.Ignore == nil || !c.Ignore.MatchString(t)) &&
			(c.Extract == nil || c.Extract.MatchString(t)) {
			i++
		} else {
			slog.Debug("Filtered release due to configuration", "release", r, "tag", t)
			rels = append(rels[:i], rels[i+1:]...)
		}
	}

	return rels
}

// GenerateChangeLog generates changelog text from given project data and configuration.
func GenerateChangeLog(c *Config, p *Project) ([]byte, error) {
	type ref struct {
		label string
		url   string
	}

	var out bytes.Buffer
	rels := c.filterReleases(p.Releases)
	heading := strings.Repeat("#", c.Level)
	url := p.RepoURL()

	slog.Debug("Start generating release notes", "url", url, "config", c)

	linker := NewReflinker(url)
	for _, l := range p.Autolinks {
		linker.AddExtRef(*l.KeyPrefix, *l.URLTemplate, *l.IsAlphanumeric)
	}

	userExists := make(map[string]bool)

	numRels := len(rels)
	refs := make([]ref, 0, numRels)
	for i, rel := range rels {
		prevTag := ""
		if i+1 < numRels {
			prevTag = rels[i+1].GetTagName()
		}

		title := strings.TrimSpace(rel.GetName())
		tag := rel.GetTagName()

		if tag == "" {
			return nil, fmt.Errorf(
				"release %q created at %s is not associated with any tag name. cannot determine a tag name for the release. did you forget setting tag name in the draft release?",
				strings.TrimSpace(rel.GetName()),
				rel.CreatedAt.Format(time.RFC3339),
			)
		}

		var created github.Timestamp
		if rel.GetDraft() {
			created = rel.GetCreatedAt()
		} else {
			created = rel.GetPublishedAt()
		}

		slog.Debug("Generating release", "name", title, "tag", tag, "created", created)

		var compareURL string
		if prevTag == "" {
			compareURL = fmt.Sprintf("%s/tree/%s", url, tag)
		} else {
			compareURL = fmt.Sprintf("%s/compare/%s...%s", url, prevTag, tag)
		}

		fmt.Fprintf(&out, "<a id=\"%s\"></a>\n", tag)

		if title == "" {
			title = tag
		} else if !strings.Contains(title, tag) {
			title = fmt.Sprintf("%s (%s)", title, tag)
		}

		pageURL := fmt.Sprintf("%s/releases/tag/%s", url, tag)
		date := created.Format(time.DateOnly)
		replacedBody := linker.Link(strings.Replace(rel.GetBody(), "\r", "", -1))

		fmt.Fprintf(&out, "%s [%s](%s) - %s\n\n", heading, title, pageURL, date)
		fmt.Fprint(&out, replacedBody)

		if c.Contributors {
			// Extract GitHub usernames using regex
			re := regexp.MustCompile(`\[@([a-zA-Z0-9-]+)\]\(https://github\.com/[a-zA-Z0-9-]+\)`)
			matches := re.FindAllStringSubmatch(replacedBody, -1)

			contributors := make(map[string]struct{})
			for _, match := range matches {
				if len(match) > 1 {
					contributors[match[1]] = struct{}{}
				}
			}

			usernames := make([]string, 0, len(contributors))
			for username := range contributors {
				if _, ok := userExists[username]; !ok {
					// Check if the user still exists in case the user has been deleted
					// This is to avoid 404 errors when fetching the user's profile image
					_, resp, err := p.GitHub.api.Users.Get(context.TODO(), username)
					userExist := err == nil && resp.StatusCode == http.StatusOK
					userExists[username] = userExist
				}
				if !userExists[username] {
					// Skip non-existent users
					continue
				}
				usernames = append(usernames, username)
			}

			// Add this to the Contributors section
			if len(usernames) > 0 {
				fmt.Fprintf(&out, "\n\n## Contributors\n\n")

				// Sort usernames for consistent output
				sort.Strings(usernames)

				for _, username := range usernames {
					// Add contributor with profile icon
					fmt.Fprintf(&out, "<a href=\"https://github.com/%s\"><img src=\"https://wsrv.nl/?url=https://github.com/%s.png&w=64&h=64&fit=cover&mask=circle\" width=\"64\" height=\"64\" alt=\"@%s\"></a> ",
						username, username, username)
				}
				fmt.Fprint(&out, "\n")
			}
		}

		fmt.Fprintf(&out, "\n\n[Changes][%s]\n\n\n", tag)

		refs = append(refs, ref{tag, compareURL})

		slog.Debug("Generated release", "title", title, "page", pageURL, "date", date)
	}

	slog.Debug("Generate release links", "links", len(refs))
	for _, r := range refs {
		fmt.Fprintf(&out, "[%s]: %s\n", r.label, r.url)
	}

	fmt.Fprintf(&out, "\n<!-- Generated by https://github.com/rhysd/changelog-from-release %s -->\n", version)

	slog.Debug("Finish to generate release notes", "url", url)

	return out.Bytes(), nil
}
