name: Private Repository
on:
  push:
    branches: [master]
env:
  CGO_ENABLED: 0

jobs:
  private-repo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.25.0'
      - run: go build
      - name: Get the expected output
        run: |
          curl -H "Authorization: token ${GITHUB_TOKEN}" 'https://raw.githubusercontent.com/rhysd/private-repo-test/refs/heads/main/CHANGELOG.md' > EXPECTED.md
          cat EXPECTED.md
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Generate
        run: |
          ./changelog-from-release -r 'https://github.com/rhysd/private-repo-test' > OUTPUT.md
          cat OUTPUT.md
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Check
        run: |
          diff=$(diff EXPECTED.md OUTPUT.md)
          if [[ "$diff" != "" ]]; then
            echo "$diff" >&2
            exit 1
          fi
